# Travis will use version specified in .ruby-version
language: ruby
cache: bundler
before_script:
  - bundle exec rake db:setup
  - bundle exec rake db:test:prepare
script: xvfb-run bundle exec rspec

