# Travis will use version specified in .ruby-version
language: ruby
cache: bundler
# required for ChromeDriver
addons:
  chrome: stable
services: postgresql
before_script:
  - bundle exec rails db:setup
  - bundle exec rails db:test:prepare
script: bundle exec rails spec
